#!/bin/sh

### 3D-Desktop FX by [SoD]Sgt-D (sgt-d@planetquake.com)

### SERVER & SETTINGS

if [ ! -f ~/.3ddesktop/pid ]; then
  echo Starting 3D-Desktop Server...
  3ddeskd --acquire --ewmh # kde3, gnome2
  # 3ddeskd --acquire --kde2 # kde2
  # 3ddeskd --workspaces # gnome
fi

### MODE SECTION

if [ $1 = 'mode' ]; then
  echo Mode
  if [ ! $2 ] ; then
    DVIEWS=6 ; view=$RANDOM ; let "view %= $DVIEWS"
  else
    view=$2
  fi
  case "$view" in
  0) echo Carousel ; 3ddesk --mode=carousel ;;
  1) echo PriceIsRight ; 3ddesk --mode=priceisright ;;
  2) echo Cylinder ; 3ddesk --mode=cylinder ;;
  3) echo ViewMaster ; 3ddesk --mode=viewmaster ;;
  4) echo Flip ; 3ddesk --mode=flip ;;
  5) echo Linear ; 3ddesk --mode=linear ;;
  *)
  esac
  
### VIEW1 SECTION

elif [ $1 = 'view1' ]; then
  echo View1
  if [ ! $2 ] ; then
    DVIEWS=10 ; view=$RANDOM ; let "view %= $DVIEWS"
  else
    view=$2
  fi
  case "$view" in
  0) echo Default ; 3ddesk --view=default ;;
  1) echo Pan Right ; 3ddesk --view=goright ;;
  2) echo Pan Left ; 3ddesk --view=goleft ;;
  3) echo Slide ; 3ddesk --view=slide ;;
  4) echo ViewMaster ; 3ddesk --view=nozoom ;;
  5) echo Linear ; 3ddesk --view=linear ;;
  6) echo Linear Zip ; 3ddesk --view=linearzip ;;
  7) echo Big Money ; 3ddesk --view=bigmoney ;;
  8) echo Linear '(No Zoom)' ; 3ddesk --mode=linear --nozoom ;;
  9) echo [SoD]Sgt-D ; 3ddesk --mode=flip use_breathing true ;;
  *)
  esac
  
### VIEW2 SECTION

elif [ $1 = 'view2' ]; then
  echo View2
  if [ ! $2 ] ; then
    DVIEWS=14 ; view=$RANDOM ; let "view %= $DVIEWS"
  else
    view=$2
  fi
  case "$view" in
  0) echo Carousel1 ; 3ddesk --view=carousel1 ;;
  1) echo Carousel2 ; 3ddesk --view=carousel2 ;;
  2) echo Carousel3 ; 3ddesk --view=carousel3 ;;
  3) echo Cylinder1 ; 3ddesk --view=cylinder1 ;;
  4) echo Cylinder2 ; 3ddesk --view=cylinder2 ;;
  5) echo Cylinder3 ; 3ddesk --view=cylinder3 ;;
  6) echo PriceIsRight1 ; 3ddesk --view=priceisright1 ;;
  7) echo PriceIsRight2 ; 3ddesk --view=priceisright2 ;;
  8) echo PriceIsRight3 ; 3ddesk --view=priceisright3 ;;
  9) echo Linear1 ; 3ddesk --view=linear1 ;;
  10) echo Linear2 ; 3ddesk --view=linear2 ;;
  11) echo ViewMaster1 ; 3ddesk --view=viewmaster1 ;;
  12) echo ViewMaster2 ; 3ddesk --view=viewmaster2 ;;
  13) echo Flip ; 3ddesk --view=flip ;;
  *)
  esac
fi
