#!/usr/bin/env python

import sys
import os
import os.path
import shutil

myPath = os.path.realpath(sys.argv[0])
(myDir, myName) = os.path.split(myPath)

fluxboxDir   = '../.fluxbox'
fluxspaceDir = '../.fluxspace'

buildFiles = ('Makefile', 'Makefile.am', 'Makefile.in', myName)
fluxspaceFiles = ('fluxspace.conf')

if not os.path.exists(fluxboxDir):
    print 'Creating "%s"' % fluxboxDir
    os.mkdir(fluxboxDir)
if not os.path.exists(fluxspaceDir):
    print 'Creating "%s"' % fluxspaceDir
    os.mkdir(fluxspaceDir)

print 'Copying test configuration files...'
for f in os.listdir('.'):
    if f in buildFiles:
        pass
    elif f in fluxspaceFiles:
        shutil.copy(f, fluxspaceDir)
    else:
        shutil.copy(f, fluxboxDir)
